services:

  stan:
    image: ghcr.io/jbris/stan-epidemiology:2.32.1
    stop_grace_period: 10s
    restart: always
    environment:
      USER: rstudio
      PASSWORD: pass
      ROOT: "TRUE"
      DISABLE_AUTH: "TRUE"
      R_SEED: 100
    build:
      context: .
    ports:
      - 8787:8787
    mem_limit: 6g
    mem_reservation: 2g
    volumes:
      - ./r_home:/home

networks:
  default:
    name: stan-epidemiology
